# Menu
menu:
  Home: /
  Archives: /archives
  Gallery: /gallery
  About: /about
rss: /atom.xml


# Miscellaneous
favicon: /牛.jpg
brand: /images/hexo.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/房子.mp4
  brand: /images/鹅.jpg

# Content
excerpt_link: Read More...

# MIIT ICP/IP/DOMAIN
beian:
  enable: false
  number: 
  url: https://beian.miit.gov.cn/

# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# 是否显示复制按钮
show_copy_btn: true

# Gitalk
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

# Valine
valine:
  enable: false # true
  el: 'vcomments'
  appId:
  appKey:
  notify: false
  verify: true
  avatar: 'mp'
  pageSize: '10'
  placeholder: '请输入...'